version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
  
  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui
    command: streamlit run ui/streamlit_app.py
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api